apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app: {{ .Release.Name }}-svc
  ports:
    - protocol: {{ .Values.service.appService.servicePort.protocol }}
      port: {{ .Values.service.Appservice.servicePort.port }}
      targetPort: {{ .Values.containerPort.secondAppPort }}
  type: {{ .Values.service.appService.serviceType }}
