apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Chart.Name}}-secondapp-vs
  namespace: {{ .Values.global.namespaces.secondApp }}
spec:
  hosts:
  - {{ .Values.global.hosts.springBootSecondApp }}
  gateways:
  - {{ .Values.global.gateways }}
  http:
    - match:
      - uri:
          prefix: {{ .Values.global.prefix.springBootSecondApp }}
      route:
      - destination:
          host: {{ .Values.global.destination.hostSecondApp }}
          port:
            number: {{ .Values.global.destination.port.number }}