apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name}}-vs
  namespace: {{ .Values.namespace.secondApp }}
spec:
  hosts:
    {{ .Values.hosts.springBootSecondApp }}
  gateways:
    {{ .Values.gateways }}
  http:
    - match:
      - uri:
          prefix: {{ .Values.prefix.springBootSecondApp }}
      route:
      - destination:
          host: {{ .Values.destination.hostSecondApp }}
          port:
            number: {{ .Values.destination.port.number }}