

global:
  namespaces:
    firstApp: spring-boot-app
    secondApp: spring-boot-second-app
    argo : argo
    appOfApps: app-of-apps
    istio: istio-system
    prometheus: prometheus-system
    kiali: kiali-system
    istioPlatform: istio-platform

  replicaCount: 1

  containerPort:
    firstAppPort: 8080
    secondAppPort: 8081

  appName: app

  platformName: istio-platform

  hosts:
    springBootApp: "app1.demo.hu"
    springBootSecondApp: "app2.demo.hu"

  gateway: istio-system/spring-boot-app-gateway

  prefix:
    springBootApp: /message
    springBootSecondApp: /getmessage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      optionOne: CreateNamespace=true

  project: default
  

  destinationApplication:
    server: https://kubernetes.default.svc

  source:
    targetRevision: 0.1.2
    path: dev
    pathApp: app-of-apps/dev
    pathFirstApp: firstApp
    pathSecondApp: secondApp
    pathIstioPlatform: istio-resources/templates
  
  destination:
    hostFirstApp: spring-boot-app.spring-boot-app.svc.cluster.local
    hostSecondApp: spring-boot-second-app.spring-boot-second-app.svc.cluster.local
    port:
      number: 80


source:
  repoUrlApp: https://veresattila2002.github.io/k8s_resources_for_helm/
