apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-firstapp-svc
spec:
  selector:
    app: {{ .Chart.Name }}-svc
  ports:
    - protocol: {{ .Values.service.servicePort.protocol}}
      port: {{ .Values.service.servicePort.port }}
      targetPort: {{ .Values.global.containerPort.firstAppPort }}
  type: {{ .Values.service.serviceType }}
