apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name}}-vs
  namespace: {{ .Values.namespace.firstApp }}
spec:
  hosts: 
    {{ .Values.hosts.springBootApp }}
  gateways:  
    {{ .Values.gateways }}
  http:
    - match:
      - uri:
          prefix: {{ .Values.springBootApp }}
      route:
      - destination:
          host: {{ .Values.destination.hostFirstApp }}
          port:
            number: {{ .Values.destination.port.number }}
