apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Chart.Name}}-firstapp-vs
  namespace: {{ .Values.global.namespaces.firstApp }}
spec:
  hosts: 
  - {{ .Values.global.hosts.springBootApp }}
  gateways:  
  - {{ .Values.global.gateways }}
  http:
    - match:
      - uri:
          prefix: {{ .Values.global.prefix.springBootApp }}
      route:
      - destination:
          host: {{ .Values.global.destination.hostFirstApp }}
          port:
            number: {{ .Values.destination.port.number }}
