apiVersion: v2
name: platform
description: A Helm chart for Kubernetes

type: application


version: 0.1.6


appVersion: "1.16.0"

dependencies:
- name: istio-resources
  version: 0.1.12
  repository: https://veresattila2002.github.io/k8s_resources_for_helm/