apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-application
  namespace: {{ .Values.global.namespaces.argo }}
spec:
  project: {{ .Values.global.project }}

  source:
    repoURL: {{ .Values.source.repoUrlSecondApp }}
    targetRevision: {{ .Values.global.source.targetRevision }}
    path: {{ .Values.global.source.path }}

  destination:
    server: {{ .Values.global.destinationApplication.server }}
    namespace: {{ .Values.global.namespaces.secondApp }}

  syncPolicy:
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}
    syncOptions:
      {{ .Values.global.syncPolicy.syncOptions }}
