apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-application
  namespace: {{ .Values.namespace.argo }}
spec:
  project: {{ .Values.project }}

  source:
    repoURL: {{ .Values.source.repoUrlFirstApp }}
    targetRevision: {{ .Values.source.targetRevision }}
    path: {{ .Values.source.path }}
  destination:
    server: {{ .Values.destinationApplication.server }}
    namespace: {{ .Values.namespace.firstApp }}
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.syncPolicy.automated.selfHeal }}
    syncOptions:
      - {{ .Values.syncPolicy.syncOptions }}
