apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-application
  namespace: {{ .Values.global.namespaces.argo }}
spec:
  project: {{ .Values.global.project }}

  source:
    repoURL: {{ .Values.source.repoUrlApp }}
    targetRevision: {{ .Values.global.source.targetRevision }}
    chart: {{ .Values.global.source.pathSecondApp }}
    helm:
      valueFiles:
      - values.yaml

  destination:
    server: {{ .Values.global.destinationApplication.server }}
    namespace: {{ .Values.global.namespaces.secondApp }}

  syncPolicy:
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}
    syncOptions:
    - {{ .Values.global.syncPolicy.syncOptions.optionOne }}
