apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.global.platformName }}
  namespace: {{ .Values.global.namespaces.argo }}
spec:
  project: {{ .Values.global.project }}

  source:
    repoURL: {{ .Values.source.repoUrlApp }}
    targetRevision: {{ .Values.global.source.targetRevisionIstio }}
    chart: {{ .Values.global.source.pathIstioPlatform }}
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: {{ .Values.global.destinationApplication.server }}
    namespace: {{ .Values.global.namespaces.istioPlatform }}
  syncPolicy:
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}
    syncOptions:
    - {{ .Values.global.syncPolicy.syncOptions.optionOne }}
