apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.istioConfig.name.istioBase }}
  namespace: {{ .Values.global.namespaces.istio }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: {{ .Values.istioConfig.repoUrl.istioBase }}
    chart: {{ .Values.istioConfig.chart.istioBase }}
    targetRevision: {{ .Values.istioConfig.targetRevision.istioBase }}
    helm:
      releaseName: {{ .Values.istioConfig.helm.releaseName.istioBase }}
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: {{ .Values.global.namespaces.istio }}
  syncPolicy:
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}
    syncOptions:
      - {{ .Values.global.syncPolicy.syncOptions }}