apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.istioConfig.name.prometheus }}
  namespace: {{ .Values.global.namespaces.argo}}
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: {{ .Values.istioConfig.repoUrl.prometheus }}
    chart: {{ .Values.istioConfig.chart.prometheus }}
    targetRevision: {{ .Values.istioConfig.targetRevision.prometheus }}
    helm:
      releaseName: {{ .Values.istioConfig.helm.releaseName.prometheus }}
      insecureSkipTLSVerify: {{ .Values.istioConfig.helm.insecureSkipTLSVerify.prometheus }}
  destination:
    server: {{ .Values.global.destinationApplication.server }}
    namespace: {{ .Values.global.namespaces.prometheus }}
  syncPolicy:
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}
    syncOptions:
    - {{ .Values.global.syncPolicy.syncOptions.optionOne }}