apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.istioConfig.name.prometheus }}
  namespace: {{ .Values.global.namespace.argo}}
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: {{ .Values.istioConfig.repoUrl.prometheus }}
    chart: {{ .Values.istioConfig.chart.prometheus }}
    targetRevision: {{ .Values.istioConfig.targetRevision.prometheus }}
    helm:
      releaseName: {{ .Values.istioConfig.helm.releaseName.prometheus }}
      insecureSkipTLSVerify: {{ .Values.istioConfig.helm.insecureSkipTLSVerify.prometheus }}
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: {{ .Values.global.namespace.prometheus }}
  syncPolicy:
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}
    syncOptions:
      - {{ .Values.globalsyncPolicy.syncOptions }}