

global:
  namespaces:
    firstApp: spring-boot-app
    secondApp: spring-boot-second-app
    argo : argo
    appOfApps: app-of-apps
    istio: istio-system
    prometheus: prometheus-system
    kiali: kiali-system
    istioPlatform: istio-platform

  replicaCount: 1

  containerPort:
    firstAppPort: 8080
    secondAppPort: 8081

  appName: app

  platformName: istio-platform

  hosts:
    springBootApp: "app1.demo.hu"
    springBootSecondApp: "app2.demo.hu"

  gateway: istio-system/spring-boot-app-gateway

  prefix:
    springBootApp: /message
    springBootSecondApp: /getmessage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      optionOne: CreateNamespace=true

  project: default
  

  destinationApplication:
    server: https://kubernetes.default.svc

  source:
    targetRevision: HEAD
    path: dev
    pathApp: app-of-apps/dev
    pathFirstApp: spring-boot-app-k8s-resources/templates/dev
    pathSecondApp: spring-boot-second-app-k8s-resources/templates/dev
    pathIstioPlatform: istio-resources/templates
  
  destination:
    hostFirstApp: spring-boot-app.spring-boot-app.svc.cluster.local
    hostSecondApp: spring-boot-second-app.spring-boot-second-app.svc.cluster.local
    port:
      number: 80


spring-boot-app:
  source:
    repoUrlApp: https://github.com/veresattila2002/k8s_resources_for_helm.git

  image:
    name: ghcr.io/veresattila2002/helloword
    tag: "3.0"

  service:
    servicePort:
      protocol: TCP
      port: 80
    serviceType: ClusterIP

